parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_name:     symf
    database_user:     user
    database_password: password

    mailer_transport:  mail
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            ru
    secret:            ThisTokenIsNotSoSecretChangeIt