security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    #google:             "/login/check-google"
                    #my_custom_provider: "/login/check-custom"
                    #my_github:          "/login/check-github"
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # back_office:
        #     pattern: ^/bo
        #     http_basic:
        #        realm: "Secured back office area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/post$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post/\d+/show, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/post, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
